## DEPS
FROM debian:12-slim as deps

RUN apt update && apt install curl unzip -y

## BUILD
FROM deps as build

ARG SAMPLE_DB_URL="https://edu.postgrespro.com/demo-small-en.zip"

RUN curl -o /sample.zip ${SAMPLE_DB_URL}
RUN unzip /sample.zip -d sampledb && sed -i 's/DROP DATABASE demo;//g' sampledb/*.sql

## RUN
FROM postgres:17-alpine3.23

COPY --from=build  /sampledb ./docker-entrypoint-initdb.d